services:

  postgres-core:
    image: postgres:18
    container_name: postgres-core
    restart: no
    environment:
      POSTGRES_DB: core_db
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    ports:
      - "5433:5432"
    volumes:
      - postgres-core-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank -d core_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - banking-network

  postgres-currencies:
    image: postgres:18
    container_name: postgres-currencies
    environment:
      POSTGRES_DB: currencies_db
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    ports:
      - "5434:5432"
    volumes:
      - postgres-currencies-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank -d currencies_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - banking-network

  redis:
    image: redis:8.6.0
    container_name: redis
    restart: no
    command: redis-server --maxmemory-policy volatile-ttl # При нехватке памяти удаляем ключи с TTL, у которых TTL ближе к истечению
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - banking-network

  kafka:
    image: confluentinc/cp-kafka:7.7.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - banking-network

volumes:
  postgres-core-data:
  postgres-currencies-data:
  redis-data:
  kafka-data:

networks:
  banking-network:
    driver: bridge
