services:
  postgres-core:
    image: postgres:18
    container_name: postgres-core
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: core_db
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank -d core_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-core-data:/var/lib/postgresql/data
    networks:
      - banking-network

  postgres-currencies:
    image: postgres:18
    container_name: postgres-currencies
    restart: no
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: currencies_db
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank -d currencies_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-currencies-data:/var/lib/postgresql/data
    networks:
      - banking-network

  redis:
    image: redis:8.6.0
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory-policy volatile-ttl
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

volumes:
  postgres-core-data:
  postgres-currencies-data:

networks:
  banking-network:
    driver: bridge
