apiVersion: v1
kind: Service
metadata:
  name: banking-frontend
  namespace: banking-system
spec:
  selector:
    app: banking-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
