apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - banking-frontend
  - core-service
  - currencies-service
images:
  - name: ghcr.io/l1ngq/banking-frontend
    newTag: latest
  - name: ghcr.io/l1ngq/banking-core
    newTag: latest
  - name: ghcr.io/l1ngq/banking-currencies
    newTag: latest
