apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - banking-frontend
  - core-service
  - currencies-service
images:
  - name: ghcr.io/l1ngq/banking-frontend
    newTag: web-v1.0.7
  - name: ghcr.io/l1ngq/banking-core
    newTag: core-v1.0.1
  - name: ghcr.io/l1ngq/banking-currencies
    newTag: currencies-v1.0.1
