apiVersion: v1
kind: ConfigMap
metadata:
  name: core-service-config
  namespace: banking-system
data:
  DATABASE_USERNAME: postgres
  CORE_DATABASE_URL: jdbc:postgresql://postgres-core-postgresql:5432/core_db
  APP_DATABASE_SCHEMA: banking
  LIQUIBASE_SCHEMA: public
  BOOTSTRAP_SERVERS: kafka-1-kafka-chart:9092
  KAFKA_LISTENER_AUTO_STARTUP: "true"
  CURRENCIES_SERVICE_URL: http://currencies-service:8081
  REDIS_HOST: redis-master-headless
  REDIS_PORT: "6379"
  CORS_ALLOWED_ORIGINS: https://iate.space
  SCHEDULING_ENABLED: "false"
