apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    targetRevision: 85.2.2
    helm:
      values: |
        alertmanager:
          enabled: false

        grafana:
          admin:
            existingSecret: grafana-admin-credentials
            userKey: admin-user
            passwordKey: admin-password
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
          persistence:
            enabled: true
            size: 2Gi
            accessModes:
              - ReadWriteOnce
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
            hosts:
              - grafana.iate.space

        prometheusOperator:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        additionalPrometheusRulesMap:
          banking-simple-alerts:
            groups:
              - name: banking.general.alerts
                rules:
                  - alert: DeploymentDown
                    expr: kube_deployment_status_replicas_available{namespace="banking-system"} < 1
                    for: 2m
                    labels:
                      severity: critical
                    annotations:
                      summary: "Сервис {{ $labels.deployment }} недоступен!"
                      description: "В banking-system деплоймент {{ $labels.deployment }} не имеет доступных реплик больше 2 минут."
                  - alert: PodHighMemory
                    expr: |
                      sum by (namespace, pod) (
                        container_memory_working_set_bytes{namespace="banking-system", container!="", image!=""}
                      )
                      /
                      sum by (namespace, pod) (
                        kube_pod_container_resource_limits{namespace="banking-system", resource="memory", unit="byte"}
                      ) > 0.85
                    for: 5m
                    labels:
                      severity: warning
                    annotations:
                      summary: "Под {{ $labels.pod }} потребляет слишком много памяти"
                      description: "Под {{ $labels.pod }} использует более 85% от заданного лимита памяти."

                  - alert: ServiceNotResponding
                    expr: up{namespace="banking-system"} == 0
                    for: 3m
                    labels:
                      severity: critical
                    annotations:
                      summary: "Таргет {{ $labels.job }} не отвечает"
                      description: "Прометеус не может собрать метрики с сервиса {{ $labels.job }}. Возможно, приложение зависло или не отвечает по сети."

        kube-state-metrics:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

        prometheus-node-exporter:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi

        prometheus:
          prometheusSpec:
            retention: 2d
            resources:
              requests:
                cpu: 300m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 1024Mi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 8Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
