apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-currencies
  namespace: banking-system
spec:
  project: banking
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: postgresql
    targetRevision: 18.6.7
    helm:
      values: |
        auth:
          existingSecret: postgres-currencies-secret
          database: "currencies_db"
        primary:
          persistence:
            size: 2Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: banking-system
