spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5434/currencies_db}
    username: ${DATABASE_USERNAME:bank}
    password: ${DATABASE_PASSWORD:bank}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_schema: ${APP_DATABASE_SCHEMA:currencies}
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    parameters:
      APP_DATABASE_SCHEMA: ${APP_DATABASE_SCHEMA:currencies}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
  web:
    error:
      include-stacktrace: never

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081

logging:
  level:
    root: INFO
    com.bank: DEBUG
