apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-master
  namespace: argocd
spec:
  project: banking
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: redis
    targetRevision: 25.5.3
    helm:
      values: |
        architecture: standalone
        auth:
          enabled: true
          existingSecret: redis-secret
        master:
          persistence:
            size: 1Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: banking-system
