spring:
  datasource:
    url: ${CORE_DATABASE_URL:jdbc:postgresql://localhost:5433/core_db}
    username: ${DATABASE_USERNAME:bank}
    password: ${DATABASE_PASSWORD:bank}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_schema: ${APP_DATABASE_SCHEMA:banking}
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    liquibase-schema: ${LIQUIBASE_SCHEMA:public}
    default-schema: ${APP_DATABASE_SCHEMA:banking}
    parameters:
      APP_DATABASE_SCHEMA: ${APP_DATABASE_SCHEMA:banking}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  web:
    error:
      include-stacktrace: never
  task:
    scheduling:
      enabled: ${SCHEDULING_ENABLED:false}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      auto-startup: ${KAFKA_LISTENER_AUTO_STARTUP:false}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: banking-core
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: latest
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.bank.common.event"

currencies:
  service:
    url: ${CURRENCIES_SERVICE_URL:http://localhost:8081}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        same-site: lax

logging:
  level:
    root: INFO
    com.bank: DEBUG
