apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-image-updater.yaml
  - kafka/kafka-app.yaml
  - monitoring
  - postgres-core/postgres-core-app.yaml
  - postgres-currencies/postgres-currencies-app.yaml
  - redis/redis-app.yaml
