name: Deploy Core Service

on:
  push:
    tags:
      - "core-v*.*.*"
  workflow_dispatch:
    inputs:
      release_tag:
        description: Release tag to deploy
        required: true
        type: string
        default: ""

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/banking-core
  RELEASE_TAG: ${{ github.event.inputs.release_tag || github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7.2.0
        with:
          context: ./backend/banking-system-v1
          file: ./backend/banking-system-v1/Dockerfile
          build-args: |
            SERVICE=core-service
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
