name: Frontend CI

on:
  pull_request:
    branches: ["main"]
    paths:
      - "web/**"
      - ".github/workflows/frontend-ci.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "24.x"
          cache: "npm"
          cache-dependency-path: "web/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Build
        run: npm run build
